apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: 032073356223.dkr.ecr.us-east-1.amazonaws.com/employee-app:v1
          ports:
            - containerPort: 3000    




